#!/bin/bash
echo "build_hsflowd on platform:  $1"
echo "with Nvidia NVML extension"

git clone https://github.com/sflow/host-sflow \
&& cd host-sflow \
&& make rpm FEATURES="PCAP TCP DOCKER NVML"

echo "=== ldd check ========="
ldd src/Linux/mod_nvml.so
echo "======================="

for rpm in `ls *.rpm`; do cp "$rpm" "/packages/${rpm/hsflowd/hsflowd-$1}"; done
echo ""
echo "files in /packages:"
ls -l /packages

