#!/bin/bash
echo "build_hsflowd on platform:  $1"

git clone https://github.com/sflow/host-sflow \
&& cd host-sflow \
&& make rpm FEATURES="TCP DOCKER KVM OVS DBUS SYSTEMD PSAMPLE DENT"

for rpm in `ls *.rpm`; do cp "$rpm" "/packages/${rpm/hsflowd/hsflowd-$1}"; done
echo ""
echo "files in /packages:"
ls -l /packages

