#!/bin/bash

CHROOTDIR="$BASEDIR"
DAEMON="hsflowd"
CONF_F="${BASEDIR}/etc/${DAEMON}.conf"
MANI_F="${BASEDIR}/var/svc/manifest/site/${DAEMON}.xml"

if [ -f "${CONF_F}.old" ]; then
	$BASEDIR/bin/mv "${CONF_F}.old" "$CONF_F";
fi 

${BASEDIR}/usr/sbin/chroot ${CHROOTDIR} /usr/sbin/svccfg import "$MANI_F"
${BASEDIR}/usr/sbin/chroot ${CHROOTDIR} /usr/sbin/svcadm enable "$DAEMON"

exit 0
