#!/bin/bash
echo "build_hsflowd on platform:  $1"

mkdir -p /packages && chown 777 /packages

git clone https://github.com/sflow/host-sflow \
&& cd host-sflow \
&& make deb FEATURES="OPX" OPT="-g"

echo "=== ldd check ========="
ldd src/Linux/mod_opx.so
echo "======================="

for deb in `ls *.deb`; do cp "$deb" "/packages/${deb/hsflowd/hsflowd-$1}"; done
echo ""
echo "files in /packages:"
ls -l /packages

